# curso é pra 70% prático


# REVISAO

# FORMA list comprehension
# listas_peoes = ["pea"]*8
# lista_peças = ["tor","cav","bis","rai","rei","bis","cav","tor"]
# tabuleiro = [["[   ]" for casa in range(8)] for _in range(8)]
# #lembrar fazer copias das listas  para nao alterar da mesma 
# tabuleiro[0] = lista_peças.copy()
# tabuleiro[1] = lista_peoes.copy()
# tabuleiro[-1] = lista_peças[::-1]
# tabuleiro[-2] = lista_peoes.copy()

# #movimentando as peças
# tabuleiro[2][4] = tabuleiro[1][4]
# tabuleiro[1][4] = "[ ]"

# for linha in tabuleiro:

# ------------------------------------------------------
# revisão funções
# retornar o codigo objetivo

# definição função -  def
# def nome_função():
#     código
# ANOTAÇÃO RAISSA

# USO RETURN - NAO PRECISA PARENTESES
# CARACTERISTICA TUPLA PARENTESES E ITEM SEPARADO PELA VIRGULA

# FOTOS


# - - __INIT__.PY INDICA UM BIBLIOTECA E FICA MAIS ESTRUTURADO


# SOURCE SRC - TODO DIRETORIO
##############################################

#Lista Funções

# #1
# def saudacao():
#   print("Olá, bem-vindo ao Python!")
# saudacao()

# #2
# def dobro(num1):
#   return num1*2

# resultado = dobro(7)
# print(resultado)

# #3
# # def soma(num1+num2):
# #   return(num1+num2)

